sudo: required
services:
  - docker

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec api npm run test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app:
    master: awesome-expensify
    develop: awesome-expensify-qa

notifications:
  slack: kentsclub:usyDxwg8QdASFIucMiO06rWF
  email: false
