sudo: required
services:
  - docker

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec api npm run test

notifications:
  slack: kentsclub:usyDxwg8QdASFIucMiO06rWF
  email: false
