sudo: required
services:
  - docker

before_install:
  - docker build -t dinhhuyams/exppensify-backend -f Dockerfile.dev .

script:
  - docker run dinhhuyams/exppensify-backend npm run test

notifications:
  slack: kentsclub:usyDxwg8QdASFIucMiO06rWF
  email: false
